### ISSUE TITLE
Add a copy button for code snippets in the docs

### ISSUE THREAD

**Issue by edrogers** [JoshKarpel/spiel#184]
Since the Quick Start [kicks off with a 14 line snippet of code to copy-paste](https://www.spiel.how/quickstart/), it would be nice to have a copy-to-clipboard button handy. (GitHub provides one by default with code blocks, but mkdocs material theme requires a feature to be enabled in the theme for this.)

I'll make a quick PR for your consideration here

**Comment by JoshKarpel** [comment]
That'd be fantastic @edrogers  - great idea, and I'm always happy when it turns out the material theme already has the feature! 😁
